from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDesktopWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setWindowTitle('Recruit')

        # move mainwindow to center of desktop
        qr = MainWindow.frameGeometry()
        cp = QDesktopWidget().availableGeometry().center()
        qr.moveCenter(cp)
        MainWindow.move(qr.topLeft())

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.postionEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.postionEdit.setGeometry(QtCore.QRect(20, 40, 150, 30))
        self.postionEdit.setObjectName("postionEdit")
        self.keywordEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.keywordEdit.setGeometry(QtCore.QRect(180, 40, 300, 30))
        self.keywordEdit.setObjectName("keywordEdit")
        self.serchBtn = QtWidgets.QPushButton(self.centralwidget)
        self.serchBtn.setGeometry(QtCore.QRect(490, 40, 300, 30))
        self.serchBtn.setObjectName("serchBtn")
        self.listView = QtWidgets.QListView(self.centralwidget)
        self.listView.setGeometry(QtCore.QRect(490, 79, 301, 461))
        self.listView.setObjectName("listView")
        self.PostionLabel = QtWidgets.QLabel(self.centralwidget)
        self.PostionLabel.setGeometry(QtCore.QRect(20, 5, 150, 30))
        self.PostionLabel.setObjectName("PostionLabel")
        self.KeywordLabel = QtWidgets.QLabel(self.centralwidget)
        self.KeywordLabel.setGeometry(QtCore.QRect(180, 5, 300, 30))
        self.KeywordLabel.setObjectName("KeywordLabel")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(20, 79, 461, 461))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.SalaryImage = QtWidgets.QLabel(self.splitter_2)
        self.SalaryImage.setAlignment(QtCore.Qt.AlignCenter)
        self.SalaryImage.setObjectName("SalaryImage")
        self.PostionImage = QtWidgets.QLabel(self.splitter_2)
        self.PostionImage.setAlignment(QtCore.Qt.AlignCenter)
        self.PostionImage.setObjectName("PostionImage")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 28))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.serchBtn.setText(_translate("MainWindow", "search"))
        self.PostionLabel.setText(_translate("MainWindow", "postion:"))
        self.KeywordLabel.setText(_translate("MainWindow", "Key word:"))
        self.SalaryImage.setText(_translate("MainWindow", "Salary Image"))
        self.PostionImage.setText(_translate("MainWindow", "Postion Image"))